"""added password field

Revision ID: 386ba563b726
Revises: f89a23c143ea
Create Date: 2024-04-06 14:51:47.107480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386ba563b726'
down_revision = 'f89a23c143ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
